version: "3.6"

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  gitlab-runner-data:
  gitlab-runner-sock:


configs:
  gitlab:
    file: ./gitlab.rb

networks:
  gitlab-net:


services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: unless-stopped
    hostname: localhost
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/etc/gitlab/omnibus-config.rb')"
    configs:
      - source: gitlab
        target: /etc/gitlab/omnibus-config.rb
    ports:
      - "44324:44324"
      - "2224:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    shm_size: 256m
    networks:
      - gitlab-net

  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:alpine
    restart: unless-stopped
    env_file: gitlab-runner.env
    depends_on:
      - gitlab
    volumes:
      - gitlab-runner-data:/etc/gitlab-runner
      - gitlab-runner-sock:/var/run/docker.sock
    networks:
      - gitlab-net
