version: "3.6"

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:

configs:
  gitlab:
    file: ./gitlab.rb

services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/etc/gitlab/omnibus-config.rb')"
    configs:
      - source: gitlab
        target: /etc/gitlab/omnibus-config.rb
    ports:
      - "44324:44324"
      - "2224:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    shm_size: 256m

